{{- if .Values.ollama.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "localgpt.fullname" . }}-ollama
  labels:
    {{- include "localgpt.labels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "localgpt.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ollama
  template:
    metadata:
      labels:
        {{- include "localgpt.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ollama
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: ollama
        image: {{ include "localgpt.image" .Values.ollama.image }}
        imagePullPolicy: {{ include "localgpt.imagePullPolicy" .Values.ollama.image }}
        ports:
        - name: http
          containerPort: 11434
          protocol: TCP
        env:
        - name: OLLAMA_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ include "localgpt.fullname" . }}-config
              key: OLLAMA_HOST
        {{- range $key, $value := .Values.ollama.env }}
        {{- if ne $key "OLLAMA_HOST" }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /api/tags
            port: http
          initialDelaySeconds: {{ .Values.healthCheck.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthCheck.periodSeconds }}
          timeoutSeconds: {{ .Values.healthCheck.timeoutSeconds }}
          failureThreshold: {{ .Values.healthCheck.failureThreshold }}
        readinessProbe:
          httpGet:
            path: /api/tags
            port: http
          initialDelaySeconds: {{ .Values.healthCheck.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthCheck.periodSeconds }}
          timeoutSeconds: {{ .Values.healthCheck.timeoutSeconds }}
          failureThreshold: {{ .Values.healthCheck.failureThreshold }}
        resources:
          {{- toYaml .Values.ollama.resources | nindent 10 }}
        {{- if .Values.ollama.persistence.enabled }}
        volumeMounts:
        - name: data
          mountPath: /root/.ollama
        {{- end }}
      {{- if .Values.ollama.persistence.enabled }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Values.ollama.persistence.existingClaim | default (printf "%s-ollama-data" (include "localgpt.fullname" .)) }}
      {{- end }}
      {{- with .Values.ollama.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ollama.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ollama.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
