{{- if .Values.ollama.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "localgpt.fullname" . }}-ollama
  labels:
    {{- include "localgpt.labels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
  {{- with .Values.ollama.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.ollama.service.type }}
  ports:
  - port: {{ .Values.ollama.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "localgpt.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
{{- end }}
